Delete a visualisation set
gisaia/ARLAS-wui-builder pull request #376
Opened 2020-11-30 18:47 UTC by MohamedHamouGisaia

- layers can be created without setting a visualisation set

#345

2020-11-30 18:55 UTC, mbarbet requested changes

2020-11-30 18:55 UTC, mbarbet commented on src/app/modules/map-config/components/visualisations/visualisations.component.ts
> +      data: { message: 'delete the visualisation set' }
Where is the i18n files?

2020-12-01 08:17 UTC, MohamedHamouGisaia commented on src/app/modules/map-config/components/visualisations/visualisations.component.ts
> +      data: { message: 'delete the visualisation set' }
Fixed

2020-12-01 09:22 UTC, mbarbet approved these changes

2020-12-01 09:36 UTC, merged