Enable the previewed layer
gisaia/ARLAS-wui-builder pull request #538
Opened 2021-04-19 07:49 UTC by MohamedHamouGisaia

Fix #491

2021-04-19 08:08 UTC, sebbousquet requested changes

2021-04-19 08:08 UTC, sebbousquet commented on src/app/services/main-form-manager/config-export-helper.ts
> +                enabled: (enableByDefault === true) ? true : visu.value.displayed
```suggestion
                enabled: enableByDefault ? true : visu.value.displayed
```

2021-04-19 08:08 UTC, sebbousquet commented on src/app/services/main-form-manager/config-export-helper.ts
> +                        enabled: (enableByDefault === true) ? true : visu.value.displayed
```suggestion
                        enabled: enableByDefault ? true : visu.value.displayed
```

2021-04-19 08:10 UTC, MohamedHamouGisaia commented on src/app/services/main-form-manager/config-export-helper.ts
> +                enabled: (enableByDefault === true) ? true : visu.value.displayed
fixed

2021-04-19 08:10 UTC, MohamedHamouGisaia commented on src/app/services/main-form-manager/config-export-helper.ts
> +                        enabled: (enableByDefault === true) ? true : visu.value.displayed
fixed

2021-04-19 08:11 UTC, sebbousquet approved these changes

2021-04-20 17:28 UTC, mbarbet approved these changes

2021-04-21 07:27 UTC, merged